### PR TITLE
Add client_max_body_size to nginx sample

### PR DESCRIPTION
**Pull request by lorenzgith**
The standard upload size limit of php prevents the upload of large files.
By adding the option "client_max_body_size" to the nginx configuration file this can be adjusted manually.

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
Such an option would bring too many problems:
1. A lot of people are using Filestash to transfer files larger than 1G
2. Filestash isn't made in PHP, the relevant configuration and options are made via its config that can be change from the admin console. This option have no reason to be different
3 Files are streamed to their destination without being stored on disk/memory which make the idea of such an option unnecessary

**Comment by lorenzgith** [comment]
Hello @mickael-kerjean 

Thanks for the feedback.

> A lot of people are using Filestash to transfer files larger than 1G

Our colleagues from @Ressort-Informatik and we had the problem that uploads are only possible up to a few MBs via the sftp backend, about 10-20 MB. 
The limit is set so low in PHP by default.
The 1024 MB are only something like a recommendation. So that larger uploads are possible at all.


> Filestash isn't made in PHP, the relevant configuration and options are made via its config that can be changed from the admin console. This option have no reason to be different

> Files are streamed to their destination without being stored on disk/memory which make the idea of such an option unnecessary

Nowhere in the Admin Console is there an option where this can be set. Finally, our fix raises the default upload limit of PHP and thus also of Filestash.

With this entry in the nginx configuration, we were both able to solve the problem.
Issue #256 seems to be a different problem.

Greetings

**Comment by lorenzgith** [comment]
A brief summary:
We could solve the problem with this setting in both completely different independent environments.

**Comment by mickael-kerjean** [comment]
I don't really understand your points:

> Nowhere in the Admin Console is there an option where this can be set

It's not configurable as I haven't seen anyone hitting the limits. Those are set deep in the code both in term of timeout and buffer size but to my knowledge the buffer isn't relevant for the end user in that the content is streamed and never persisted into server memory / disk

> Finally, our fix raises the default upload limit of PHP and thus also of Filestash.

Filestash isn't made in PHP

**Comment by mickael-kerjean** [comment]
Just got to realise, client_max_body_size default to 1MiB when not specified directly

**Pull request merged**
